name: Crowdin Sync

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main
    paths:
      - '*.json'
      - crowdin.yml
  workflow_dispatch:

permissions:
  contents: write

jobs:
  synchronize-with-crowdin:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dynamic fix syntax
        run: |
          cp EN.json /tmp/EN.json.orig
          python3 -c "import re; f=open('EN.json', 'r+'); content=f.read(); f.seek(0); f.write(re.sub(r',\s*([\]}])', r'\1', content)); f.truncate()"
          git update-index --assume-unchanged EN.json

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          create_pull_request: false
          push_translations: true
          localization_branch_name: main
          commit_message: "New translation from Crowdin"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Restore orig EN.json
        if: always()
        run: |
          git update-index --no-assume-unchanged EN.json
          mv /tmp/EN.json.orig EN.json
