name: Sync

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Add upstream and sync
        run: |
          git config user.name "ExpieIndex"
          git config user.email "expieindex@users.noreply.github.com"
          git remote add upstream https://github.com/Orsoniks/scavgame-locale.git
          git fetch upstream main
          git merge upstream/main --no-edit || (echo "Merge conflict detected" && exit 1)
          git push origin main
